# Site settings
title: simplyDK
email: dkknguyen23@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Come here from time to time to find small treasures and surprises.
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://simplydk.com
github_username: simplydk

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
