# Site settings
title: SimplyDK
description: > # this means to ignore newlines until "baseurl:"
  This here be the description of this glorious site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  simplydk

# Build settings
markdown: kramdown
